### ISSUE TITLE
Feature Request: Add Icon for light entities

### ISSUE THREAD

**Issue by mx4k** [Gh61/lovelace-hue-like-light-card#125]
Hi, great work so far! Thanks a lot!

If it's possible, would you please add a way to set icon for light entites?

Or am I just to dumb to use them properly?

My settings looks like this:

`entities:
  - entity: light.wohnzimmer_sofa
    icon: hue:signe-gradient-floor
  - entity: light.wohnzimmer_vitrine_oben
    icon: hue:signe-gradient-table
  - entity: light.wohnzimmer_vitrine
    icon: hue:plug-eu-group`

And this is the outcome:

![grafik](https://github.com/Gh61/lovelace-hue-like-light-card/assets/8719632/1e11c3e7-52d9-4272-9d7e-6bb19ae11882)

**Comment by Gh61** [comment]
Hi, thank you.

Setting icons on entities is not an option on this card, because you can (and you should) set icons for your lights at global level.
That means going into Settings > Entities in Home Assistant and set icons to your lights here.

Direct link for you:
[![Open your Home Assistant instance and show your entities.](https://my.home-assistant.io/badges/entities.svg)](https://my.home-assistant.io/redirect/entities/)
