### ISSUE TITLE
Collapse scene area on card when there are no scenes and when using area be able to configure sorting of the lights

### ISSUE THREAD

**Issue by Liam-Whiteside** [Gh61/lovelace-hue-like-light-card#136]
I'm using scenes:[] for certain instances of the card as I don't have or need any scenes for those lights. It would be nice if the scene area of the card could collapse so that the lights are immediately under the slider. (I couldn't get this to work using card_mod, I suspect as it's the pop up dialogue rather than the card istelf).

Also when using an area to specify the entities, it would be good if there was a way to configure sorting the lights (I realise I can manually specify the entities to get around this)

**Comment by Gh61** [comment]
Hi,

I've let the scenes area there, to have some space for the color picker in light detail, because i didn't want to change the size of the dialog, when it's already open.
As you've figured out, the card_mod is not working on the dialog, as it's not child of the card.

As of the area option, i can only add some ordering based on name (similar to [Scene Order](https://github.com/Gh61/lovelace-hue-like-light-card#scene-order)), but I think the HA is already returning the light entities based on their name.
As you suggested, if you really want some specific order, you can list the entities manually.

I wanted to suggest, that you can use combination of `entities` and `area` options. When entities are rendered first and then the area lights are added at the end.
But I found, that I forget to remove the already rendered lights from loaded area lights.
So in the current state you get your defined lights and then all lights from area (including duplicates).
This will be fixed in the next version (I've created the issue #139 for this).
