### ISSUE TITLE
hue screen - vertical list of lights?

### ISSUE THREAD

**Issue by mcrummett** [Gh61/lovelace-hue-like-light-card#161]
Is it possible to have the lights in a room show in neater rows and columns rather than one long horizontal scroll?

**Comment by Gh61** [comment]
This cards primary focus is to replicate the original Hue design.
That's why there's the single long row of lights. 

I also see, why they created this layout. When you open the light's detail (color-wheel picker), you are left with a little space on the bottom (on some phone screens there is not enough space left for second row).
