### ISSUE TITLE
Color temperature outside of supported range

### ISSUE THREAD

**Issue by hvddrift** [Gh61/lovelace-hue-like-light-card#61]
I have mostly IKEA lights with temperature and brightness control only. However the temperature control seems buggy. When I slide it to cool or warm temp on the circle control it (bounces or flicks) back.

Thought it may have been computer or user error.

But on the HUE lights I have it works perfectly.

Looking at the attributes could this be the issue?

Hue Bulb
min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500

IKEA Bulb
min_color_temp_kelvin: 2202
max_colortemp kelvin: 4000
minmireds: 250
max mireds: 454

The 4000 to 6535 range? The circle for temp range is built for hue so when I slide to the bottom for example it says no, you are 2535 Kevin away and snaps back?

PS. Love your card. Changed my whole dashboard.

**Comment by Gh61** [comment]
Hi, thank you for reporting.
I think it might be the issue you are suggesting.

I assumed, that when I try to set higher temperature, than the light can handle, that it will be automatically corrected to the nearest possible value.
I guess I was wrong.

So I will change this behaviour to do this auto-correct myself.

Just to be sure, when you change the temperature only a little bit (so that the value should be inside you light's supported range), does it work as expected?

**Comment by hvddrift** [comment]
Its hard to explain, but this might help. 

in pairs, warmest color at top.
![chrome_yvzeS5uUxr](https://github.com/Gh61/lovelace-hue-like-light-card/assets/972926/bcaa61ff-131a-4e10-af31-c959634df9b5)

and on HUE card
![chrome_tUyWUgSAbE](https://github.com/Gh61/lovelace-hue-like-light-card/assets/972926/ec1acc9a-3890-4a4d-a86e-9bbc46d6f846)

And Coolest
![chrome_l8YrhLR9wb](https://github.com/Gh61/lovelace-hue-like-light-card/assets/972926/37120a45-c696-467c-afca-56d72d6f2dbc)


![chrome_URVeqnowGw](https://github.com/Gh61/lovelace-hue-like-light-card/assets/972926/b912a600-c093-4d7f-9668-452b81158ffd)
171)

If I pull below the red line it snaps back.

**Comment by Gh61** [comment]
Oh, I see, 
thank you for the details.

**Comment by Gh61** [comment]
Fixed. Will be part of the next Release.
